### PR TITLE
Add option to always close overlay

### LINKED ISSUE #47: Lossless scaling not always working correctly after the overlay closes
Lossless scaling is a tool that uses frame interpolation to generate intermediary frames from an existing picture in games. When using it with poe2 with this tool open, when exiting the overlay after price checking it will not always re-attach itself to the poe2 process and it instead still sees the 'hidden' overlay from this tool. It also seems to happen at other random times when this tool is open, but I don't know what causes that.

A way to work around this would be to add an option in the settings to always close the overlay instead of hiding it under certain situations.

### PR DESCRIPTION
**Pull request by Barragek0**
Fixes #47

I haven't tested this, but it should work fine.

### CODE REVIEW

**Review by Kvan7 — COMMENTED** [review]
Correct me if I'm wrong, but basically adding an option to always run the else for background clicks?

**Comment by Kvan7** [comment]
Also changing this to merge into dev, since master has gh actions on it

**Comment by Barragek0** [comment]
> Correct me if I'm wrong, but basically adding an option to always run the else for background clicks?

Yeah, and for when closing price check window. I realise they could be combined with an or operator, but I'm not exactly sure what !Host.isElectron is doing or if retaining the order is important, which is why I put it separately at the top.

**Comment by Kvan7** [comment]
Looks good to me, I'm not fully sure about what is going on, just since I don't have this issue. But adding it as an option seems to not break anything, so I think this is good to go. 

Since I don't have a way to reproduce/know the problem fully I'm going to leave the issue open until a release with this change comes out then you can confirm that this fixes it.

**Pull request merged**
